const root=document.querySelector('#admin');const KEY='fm_state';
function get(){try{return JSON.parse(localStorage.getItem(KEY))||{articles:[],affirmations:[]}}catch{return {articles:[],affirmations:[]}}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
if(sessionStorage.getItem('fm_admin')!=='1'){root.innerHTML=`<div class="hero"><span class="eyebrow">Founder Admin</span><h1>لوحة إدارة Féminine Mind</h1><p>لأغراض الأمان، لا تضعي كلمة مرور حقيقية داخل ملفات الواجهة. هذه نسخة محلية جاهزة للربط بنظام مصادقة آمن عند النشر.</p><div class="field"><label>رمز الدخول التجريبي</label><input class="input" id="pass" type="password"></div><button class="btn full" onclick="login()">دخول</button><button class="btn secondary full" onclick="location.href='index.html'">العودة للمنصة</button></div>`}else dashboard();
function login(){if(document.querySelector('#pass').value==='FEMININE'){sessionStorage.setItem('fm_admin','1');dashboard()}else alert('رمز غير صحيح')}
function dashboard(){const s=get();root.innerHTML=`<div class="hero"><span class="eyebrow">Founder Dashboard</span><h1>إدارة المحتوى</h1><p>هذه الطبقة محلية في النسخة المجانية. عند النشر الحقيقي تُستبدل بتوثيق آمن وقاعدة بيانات.</p></div>
<div class="section-title"><h2>إضافة مقال</h2></div><div class="card"><div class="field"><label>العنوان</label><input id="title" class="input"></div><div class="field"><label>التصنيف</label><input id="cat" class="input" value="الوعي الذاتي"></div><div class="field"><label>المحتوى</label><textarea id="text" class="input" rows="5"></textarea></div><label><input type="checkbox" id="free" checked> مجاني</label><button class="btn full" onclick="addArticle()">حفظ المقال</button></div>
<div class="section-title"><h2>إضافة توكيد</h2></div><div class="card"><input id="affirm" class="input" placeholder="توكيد جديد"><button class="btn full" onclick="addAffirm()">حفظ التوكيد</button></div>
<div class="section-title"><h2>المقالات الحالية</h2></div><div class="list">${s.articles.map(a=>`<div class="card"><span class="pill">${a.free?'مجاني':'Premium'}</span><h3>${esc(a.title)}</h3><p>${esc(a.text)}</p><button class="btn secondary" onclick="del(${a.id})">حذف</button></div>`).join('')}</div>
<div class="section-title"><h2>المحتوى التلقائي — البنية</h2></div><div class="card"><p>يومياً: توكيد + تمرين + سلوك. أسبوعياً: مقال. هذه النسخة تعرض المحرك محلياً؛ ربط AI والجدولة الحقيقية يحتاج Backend ومفتاح خدمة AI بعد النشر.</p></div>
<button class="btn secondary full" onclick="sessionStorage.removeItem('fm_admin');location.reload()">تسجيل الخروج</button><button class="btn full" onclick="location.href='index.html'">العودة للمنصة</button>`}
function addArticle(){const s=get();s.articles.unshift({id:Date.now(),title:document.querySelector('#title').value.trim()||'مقال جديد',cat:document.querySelector('#cat').value.trim()||'الوعي الذاتي',free:document.querySelector('#free').checked,date:'أضيف من الإدارة',text:document.querySelector('#text').value.trim()||'اكتبي المحتوى هنا.'});save(s);dashboard()}
function addAffirm(){const s=get();const v=document.querySelector('#affirm').value.trim();if(v){s.affirmations.unshift(v);save(s)}dashboard()}
function del(id){const s=get();s.articles=s.articles.filter(a=>a.id!==id);save(s);dashboard()}
